import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "izitoast/dist/css/iziToast.min.css";
import "overlayscrollbars/overlayscrollbars.css";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { OverlayScrollbarsComponent } from "overlayscrollbars-react";
import GlobalScrollbar from "@/components/globalScrollbar/globalScrollbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <GlobalScrollbar>
          <TanStackProvider>{children}</TanStackProvider>
        </GlobalScrollbar>
      </body>
    </html>
  );
}
